apiVersion: v1

kind: Service 

metadata:
  name: slot-management-service
  labels:
    app: slot-management-service-svc-label

spec:
  ports:
  - port: 8084
    name: http

  selector:
    app: slot-management-service-v1-v2

  type: LoadBalancer

---

apiVersion: apps/v1

kind: Deployment

metadata:
  name: slot-management-service-deployment-v1
  labels:
    app: slot-management-service-dep-label

spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: slot-management-service-v1-v2

  template: # template for the pods
    metadata:
      labels:
        app: slot-management-service-v1-v2
        version: v1

    spec:
      containers:
      - name: slot-management-service-ver1
        image: gcr.io/dulcet-listener-317509/slot-management-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8890